workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app-store
        bundle_identifier: com.christen.vetted
        automatic_code_signing: true

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
