workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.christen.vetted

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Bump iOS deployment target to 14
        script: |
          echo "Updating iOS deployment target to 14 in Generated.xcconfig..."
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g' ios/Flutter/Generated.xcconfig

      - name: Pre-warm iOS build files
        script: |
          flutter build ios --debug --no-codesign

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
